package com.sidakmanchanda.zookdns;

public enum RecordType {A,NS,MD,MF,CNAME,SOA,MB,MG,MR,NULL,WKS,PTR,HINFO,MINFO,MX,TXT,RP,AFSDB,X25,ISDN,RT,NSAP,NSAP_PTR,SIG,KEY,PX,GPOS,AAAA,LOC,NXT,EID,NIMLOC,SRV}

